// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_23CV.Context;

namespace ProyectoFinal_23CV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230724122745_mai")]
    partial class mai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("PkDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FkProducto")
                        .HasColumnType("int");

                    b.Property<int>("FkVenta")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoPkProducto")
                        .HasColumnType("int");

                    b.Property<int>("VentaPkVenta")
                        .HasColumnType("int");

                    b.HasKey("PkDetalleVenta");

                    b.HasIndex("ProductoPkProducto");

                    b.HasIndex("VentaPkVenta");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Producto", b =>
                {
                    b.Property<int>("PkProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PrecioProducto")
                        .HasColumnType("double");

                    b.HasKey("PkProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Venta", b =>
                {
                    b.Property<int>("PkVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime");

                    b.Property<int?>("FkProducto")
                        .HasColumnType("int");

                    b.Property<int?>("FkVendedor")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnType("double");

                    b.Property<double>("Subtotal")
                        .HasColumnType("double");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("PkVenta");

                    b.HasIndex("FkProducto");

                    b.HasIndex("FkVendedor");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.DetalleVenta", b =>
                {
                    b.HasOne("ProyectoFinal_23CV.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoPkProducto");

                    b.HasOne("ProyectoFinal_23CV.Entities.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaPkVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoFinal_23CV.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Venta", b =>
                {
                    b.HasOne("ProyectoFinal_23CV.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("FkProducto");

                    b.HasOne("ProyectoFinal_23CV.Entities.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("FkVendedor");

                    b.Navigation("Producto");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
